import { test, expect, webkit, devices } from '@playwright/test';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import JSZip from 'jszip';
import sharp from 'sharp';
import fs from 'node:fs/promises';
import path from 'node:path';

const BASE='https://dhhd-tools-v022.vercel.app';
const root=process.cwd();
const fx=path.join(root,'.fixtures');
const out=path.join(root,'test-results','downloads');
const files={simple:path.join(fx,'simple-3-pages.pdf'),one:path.join(fx,'one-page.pdf'),formMeta:path.join(fx,'form-metadata.pdf'),heavy:path.join(fx,'heavy-scan.pdf'),wide:path.join(fx,'wide-scan.pdf'),jpg:path.join(fx,'photo.jpg'),png:path.join(fx,'document.png'),webp:path.join(fx,'photo.webp'),heic:path.join(fx,'photo.heic')};

function noise(size,seed=123456789){const b=Buffer.allocUnsafe(size);let x=seed>>>0;for(let i=0;i<size;i++){x=(Math.imul(x,1664525)+1013904223)>>>0;b[i]=x>>>24}return b}
async function makePdf(file,pages=3){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);for(let i=0;i<pages;i++){const p=pdf.addPage([595.28,841.89]);p.drawText(`DHHD QA PAGE ${i+1}`,{x:60,y:740,size:30,font,color:rgb(.1,.2,.6)});p.drawText('Ho so du hoc - real PDF fixture',{x:60,y:690,size:16,font});p.drawRectangle({x:55,y:120+i*15,width:420,height:180,borderWidth:2,borderColor:rgb(.7,.1,.1)})}await fs.writeFile(file,await pdf.save())}
async function makeFormMeta(){const pdf=await PDFDocument.create();pdf.setTitle('SECRET_TITLE_QA');pdf.setAuthor('DHHD_QA_AUTHOR');pdf.setSubject('PRIVATE_SUBJECT');const page=pdf.addPage([595.28,841.89]),form=pdf.getForm(),field=form.createTextField('student_name');field.setText('Nguyen Van QA');field.addToPage(page,{x:80,y:650,width:300,height:35});await fs.writeFile(files.formMeta,await pdf.save())}
async function makeHeavy(){const pdf=await PDFDocument.create();for(let n=0;n<2;n++){const w=900,h=1250,raw=noise(w*h*3,1000+n),jpg=await sharp(raw,{raw:{width:w,height:h,channels:3}}).jpeg({quality:96,chromaSubsampling:'4:4:4'}).toBuffer(),img=await pdf.embedJpg(jpg),p=pdf.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}await fs.writeFile(files.heavy,await pdf.save())}
async function makeWide(){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.HelveticaBold),p=pdf.addPage([842,595]);p.drawText('LEFT PAGE',{x:90,y:300,size:36,font});p.drawText('RIGHT PAGE',{x:505,y:300,size:36,font});p.drawLine({start:{x:421,y:0},end:{x:421,y:595},thickness:2});await fs.writeFile(files.wide,await pdf.save())}
async function makeImages(){await sharp({create:{width:900,height:1200,channels:3,background:{r:245,g:245,b:235}}}).composite([{input:Buffer.from('<svg width="900" height="1200"><rect x="60" y="80" width="780" height="1040" fill="white" stroke="black" stroke-width="5"/><text x="110" y="180" font-size="62">DHHD JPG QA</text></svg>'),top:0,left:0}]).jpeg({quality:90}).toFile(files.jpg);await sharp({create:{width:800,height:1100,channels:4,background:{r:255,g:255,b:255,alpha:1}}}).composite([{input:Buffer.from('<svg width="800" height="1100"><text x="80" y="160" font-size="58">DHHD PNG QA</text><rect x="70" y="220" width="650" height="700" fill="none" stroke="blue" stroke-width="8"/></svg>'),top:0,left:0}]).png().toFile(files.png);await sharp(files.jpg).webp({quality:88}).toFile(files.webp);const r=await fetch('https://raw.githubusercontent.com/dsoprea/heic-exif-samples/master/image1.heic');if(!r.ok)throw new Error(`HEIC fixture download failed: ${r.status}`);await fs.writeFile(files.heic,Buffer.from(await r.arrayBuffer()))}
async function fixtures(){await fs.mkdir(fx,{recursive:true});await fs.mkdir(out,{recursive:true});await makePdf(files.simple,3);await makePdf(files.one,1);await makeFormMeta();await makeHeavy();await makeWide();await makeImages()}
async function gotoTool(page,name){await page.goto(`${BASE}/#${name}`,{waitUntil:'load'});await page.waitForFunction(()=>!!window.PDFLib&&!!window.JSZip,null,{timeout:30000});await expect(page.locator('.toolHero h1')).toBeVisible()}
async function download(page,selector,name,timeout=120000){const wait=page.waitForEvent('download',{timeout});await page.locator(selector).click();const dl=await wait,dest=path.join(out,name);await dl.saveAs(dest);expect((await fs.stat(dest)).size).toBeGreaterThan(50);return dest}
async function pdf(file,count){const d=await PDFDocument.load(await fs.readFile(file));expect(d.getPageCount()).toBe(count);return d}
async function zip(file,ext,count){const z=await JSZip.loadAsync(await fs.readFile(file)),names=Object.keys(z.files).filter(n=>n.toLowerCase().endsWith(ext));expect(names.length).toBe(count);const first=await z.file(names[0]).async('uint8array');if(ext==='.jpg')expect([...first.slice(0,3)]).toEqual([255,216,255]);if(ext==='.png')expect([...first.slice(0,8)]).toEqual([137,80,78,71,13,10,26,10]);if(ext==='.pdf')expect(Buffer.from(first.slice(0,5)).toString()).toBe('%PDF-')}
async function range(page,selector,value){await page.locator(selector).evaluate((el,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))},value)}

test.beforeAll(fixtures);
test.describe.serial('DHHD Tools production real-file QA',()=>{
 test('00 home public + 23 tools',async({page})=>{const r=await page.goto(`${BASE}/#home`);expect(r.status()).toBeLessThan(400);await page.waitForFunction(()=>document.querySelectorAll('[data-tool-card]').length===23);await expect(page.getByText('23 công cụ hoạt động')).toBeVisible()});
 test('01 merge',async({page})=>{await gotoTool(page,'merge');await page.setInputFiles('#mergeFiles',[files.simple,files.one]);await pdf(await download(page,'#mergeBtn','01-merge.pdf'),4)});
 test('02 split/extract',async({page})=>{await gotoTool(page,'split');await page.setInputFiles('#splitFile',files.simple);await page.locator('#range').fill('1,3');await pdf(await download(page,'#extract','02-extract.pdf'),2);await zip(await download(page,'#splitAll','02-split.zip'),'.pdf',3)});
 test('03 images to PDF',async({page})=>{await gotoTool(page,'images');await page.setInputFiles('#imgs',[files.jpg,files.png]);await pdf(await download(page,'#make','03-images.pdf'),2)});
 test('04 rotate',async({page})=>{await gotoTool(page,'rotate');await page.setInputFiles('#rot',files.simple);const d=await pdf(await download(page,'#go','04-rotate.pdf'),3);expect(d.getPage(0).getRotation().angle).toBe(90)});
 test('05 watermark VI',async({page})=>{await gotoTool(page,'watermark');await page.setInputFiles('#wm',files.simple);await page.locator('#wtext').fill('DU HỌC HẢI DƯƠNG - QA');await pdf(await download(page,'#go','05-watermark.pdf'),3)});
 test('06 PDF to JPG',async({page})=>{await gotoTool(page,'jpg');await page.setInputFiles('#jpgf',files.simple);await zip(await download(page,'#go','06-jpg.zip'),'.jpg',3)});
 test('07 compress scan',async({page})=>{await gotoTool(page,'compress');await page.setInputFiles('#cmp',files.heavy);const f=await download(page,'#go','07-compress.pdf');await pdf(f,2);expect((await fs.stat(f)).size).toBeLessThan((await fs.stat(files.heavy)).size)});
 test('08 page numbers',async({page})=>{await gotoTool(page,'numbers');await page.setInputFiles('#numf',files.simple);await pdf(await download(page,'#go','08-numbers.pdf'),3)});
 test('09 redact',async({page})=>{await gotoTool(page,'redact');await page.setInputFiles('#redf',files.simple);await expect(page.locator('#wrap canvas')).toBeVisible();const b=await page.locator('#wrap').boundingBox();await page.mouse.move(b.x+b.width*.15,b.y+b.height*.18);await page.mouse.down();await page.mouse.move(b.x+b.width*.55,b.y+b.height*.32,{steps:8});await page.mouse.up();await pdf(await download(page,'#export','09-redact.pdf'),3)});
 test('10 PDF to PNG',async({page})=>{await gotoTool(page,'png');await page.setInputFiles('#pngf',files.simple);await zip(await download(page,'#go','10-png.zip'),'.png',3)});
 test('11 organize/delete/rotate',async({page})=>{await gotoTool(page,'organize');await page.setInputFiles('#orgf',files.simple);await expect(page.locator('.thumb')).toHaveCount(3,{timeout:30000});await page.locator('[data-del="1"]').click();await page.locator('[data-rot="0"]').click();const d=await pdf(await download(page,'#export','11-organize.pdf'),2);expect(d.getPage(0).getRotation().angle).toBe(90)});
 test('12 crop',async({page})=>{await gotoTool(page,'crop');await page.setInputFiles('#cropf',files.simple);await range(page,'#l',10);await range(page,'#r',10);const src=await PDFDocument.load(await fs.readFile(files.simple)),dst=await pdf(await download(page,'#go','12-crop.pdf'),3);expect(dst.getPage(0).getCropBox().width).toBeLessThan(src.getPage(0).getCropBox().width)});
 test('13 flatten form + raster',async({page})=>{await gotoTool(page,'flatten');await page.setInputFiles('#flatf',files.formMeta);const a=await pdf(await download(page,'#go','13-flat-form.pdf'),1);expect(a.getForm().getFields().length).toBe(0);await gotoTool(page,'flatten');await page.setInputFiles('#flatf',files.simple);await page.locator('[data-mode="raster"]').click();await pdf(await download(page,'#go','13-flat-raster.pdf'),3)});
 test('14 metadata clean',async({page})=>{await gotoTool(page,'metadata');await page.setInputFiles('#metaf',files.formMeta);const d=await pdf(await download(page,'#go','14-meta.pdf'),1);expect(d.getTitle()||'').toBe('');expect(d.getAuthor()||'').toBe('')});
 test('15 privacy clean both modes',async({page})=>{await gotoTool(page,'privacy');await page.setInputFiles('#privf',files.formMeta);const d=await pdf(await download(page,'#go','15-privacy.pdf'),1);expect(d.getTitle()||'').toBe('');await gotoTool(page,'privacy');await page.setInputFiles('#privf',files.simple);await page.locator('#raster').check();await pdf(await download(page,'#go','15-privacy-raster.pdf'),3)});
 test('16 protect AES-256 + unlock',async({page})=>{await gotoTool(page,'protect');await page.setInputFiles('#protf',files.simple);await page.locator('#pw').fill('DHHDqa2026!');await page.locator('#pw2').fill('DHHDqa2026!');const enc=await download(page,'#go','16-protected.pdf');expect((await fs.readFile(enc)).includes(Buffer.from('/Encrypt'))).toBeTruthy();await gotoTool(page,'unlock');await page.setInputFiles('#unlockf',enc);await page.locator('#pw').fill('DHHDqa2026!');await pdf(await download(page,'#go','16-unlocked.pdf'),3)});
 test('17 target compress 1MB',async({page})=>{expect((await fs.stat(files.heavy)).size).toBeGreaterThan(1048576);await gotoTool(page,'targetcompress');await page.setInputFiles('#tcf',files.heavy);await page.locator('#target').selectOption('1');const f=await download(page,'#tcgo','17-target.pdf',180000);await pdf(f,2);expect((await fs.stat(f)).size).toBeLessThanOrEqual(1048576+16384)});
 test('18 scanner',async({page})=>{await gotoTool(page,'scanner');await page.setInputFiles('#galleryInput',[files.jpg,files.png]);await expect(page.locator('#scanGo')).toBeVisible();await pdf(await download(page,'#scanGo','18-scanner.pdf'),2)});
 test('19 sign pointer',async({page})=>{await gotoTool(page,'sign');await page.setInputFiles('#signf',files.simple);const b=await page.locator('#sig').boundingBox();await page.mouse.move(b.x+80,b.y+130);await page.mouse.down();await page.mouse.move(b.x+180,b.y+80,{steps:5});await page.mouse.move(b.x+300,b.y+150,{steps:5});await page.mouse.move(b.x+440,b.y+70,{steps:5});await page.mouse.up();await pdf(await download(page,'#signGo','19-sign.pdf'),3)});
 test('20 HEIC/WebP -> JPG/PDF',async({page})=>{await gotoTool(page,'heic');await page.setInputFiles('#heicf',files.webp);await zip(await download(page,'#heicGo','20-webp.zip'),'.jpg',1);await gotoTool(page,'heic');await page.setInputFiles('#heicf',files.heic);await zip(await download(page,'#heicGo','20-heic.zip',180000),'.jpg',1);await gotoTool(page,'heic');await page.setInputFiles('#heicf',files.webp);await page.locator('[data-out="pdf"]').click();await pdf(await download(page,'#heicGo','20-webp.pdf'),1)});
 test('21 split scan',async({page})=>{await gotoTool(page,'splitscan');await page.setInputFiles('#ssf',files.wide);await pdf(await download(page,'#ssGo','21-split-scan.pdf'),2)});
 test('22 n-up 4 and 2',async({page})=>{await gotoTool(page,'nup');await page.setInputFiles('#nupf',files.simple);await pdf(await download(page,'#nupGo','22-nup4.pdf'),1);await gotoTool(page,'nup');await page.setInputFiles('#nupf',files.simple);await page.locator('#nupCount').selectOption('2');await pdf(await download(page,'#nupGo','22-nup2.pdf'),2)});
 test('23 mobile WebKit home/scanner/sign',async()=>{const browser=await webkit.launch(),ctx=await browser.newContext({...devices['iPhone 13']}),page=await ctx.newPage();await page.goto(`${BASE}/#home`);await page.waitForFunction(()=>document.querySelectorAll('[data-tool-card]').length===23);await expect(page.locator('.topbar')).toBeVisible();await page.goto(`${BASE}/#scanner`);await expect(page.locator('#cameraBtn')).toBeVisible();await page.goto(`${BASE}/#sign`);await page.setInputFiles('#signf',files.simple);await expect(page.locator('#sig')).toBeVisible();await ctx.close();await browser.close()});
});
