import { test, expect, webkit, devices } from '@playwright/test';
import { PDFDocument, StandardFonts } from 'pdf-lib';
import JSZip from 'jszip';
import sharp from 'sharp';
import fs from 'node:fs/promises';
import path from 'node:path';

const BASE='https://dhhd-tools-v022.vercel.app';
const root=process.cwd(),fx=path.join(root,'.fixtures-v07'),out=path.join(root,'test-results','v07-downloads');
const f={base:path.join(fx,'base.pdf'),size:path.join(fx,'split-size.pdf'),skew:path.join(fx,'skew.pdf'),text:path.join(fx,'markdown.pdf')};
function noise(size,seed=19){const b=Buffer.allocUnsafe(size);let x=seed>>>0;for(let i=0;i<size;i++){x=(Math.imul(x,1664525)+1013904223)>>>0;b[i]=x>>>24}return b}
async function fixtures(){
 await fs.mkdir(fx,{recursive:true});await fs.mkdir(out,{recursive:true});
 {const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);for(let i=1;i<=3;i++){const p=pdf.addPage([595.28,841.89]);p.drawText(`DHHD V07 PAGE ${i}`,{x:60,y:720,size:28,font});p.drawLine({start:{x:60,y:650},end:{x:530,y:650},thickness:2});p.drawText('Vietnam document tools QA',{x:60,y:610,size:16,font})}await fs.writeFile(f.base,await pdf.save())}
 {const pdf=await PDFDocument.create();for(let i=0;i<4;i++){const w=720,h=900,raw=noise(w*h*3,100+i),jpg=await sharp(raw,{raw:{width:w,height:h,channels:3}}).jpeg({quality:72}).toBuffer(),img=await pdf.embedJpg(jpg),p=pdf.addPage([595.28,841.89]);p.drawImage(img,{x:0,y:0,width:595.28,height:841.89})}await fs.writeFile(f.size,await pdf.save())}
 {const svg=Buffer.from(`<svg width="900" height="1200"><rect width="900" height="1200" fill="white"/><g stroke="black" stroke-width="5">${Array.from({length:15},(_,i)=>`<line x1="100" y1="${180+i*55}" x2="800" y2="${180+i*55}"/>`).join('')}</g><text x="160" y="130" font-family="Arial" font-size="52">DHHD DESKEW QA</text></svg>`),img=await sharp(svg).rotate(3,{background:'white'}).jpeg({quality:92}).toBuffer(),pdf=await PDFDocument.create(),jpg=await pdf.embedJpg(img),p=pdf.addPage([595.28,841.89]);p.drawImage(jpg,{x:0,y:0,width:595.28,height:841.89});await fs.writeFile(f.skew,await pdf.save())}
 {const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),p=pdf.addPage([595.28,841.89]);p.drawText('DHHD MARKDOWN QA',{x:60,y:740,size:30,font:bold});p.drawText('This is body text for PDF to Markdown.',{x:60,y:680,size:12,font});p.drawText('Second body line 12345',{x:60,y:650,size:12,font});await fs.writeFile(f.text,await pdf.save())}
}
const fn={splitbysize:'splitBySizeTool',longimage:'longImageTool',headerfooter:'headerFooterTool',annotate:'annotationTool',deskew:'deskewTool',markdown:'markdownTool'};
async function go(page,key){await page.goto(`${BASE}/#${key}`,{waitUntil:'load'});await page.waitForFunction(k=>typeof window[k]==='function',fn[key],{timeout:30000});await expect(page.locator('.toolHero h1')).toBeVisible()}
async function dl(page,sel,name,timeout=120000){const wait=page.waitForEvent('download',{timeout});await page.locator(sel).click();const d=await wait,p=path.join(out,name);await d.saveAs(p);expect((await fs.stat(p)).size).toBeGreaterThan(80);return p}
async function pdf(file,count){const d=await PDFDocument.load(await fs.readFile(file));expect(d.getPageCount()).toBe(count);return d}
test.beforeAll(fixtures);
test.describe.serial('DHHD v0.7 public production real-file gate',()=>{
 test('40 split PDF by 1MB produces valid bounded chunks',async({page})=>{await go(page,'splitbysize');await page.setInputFiles('#sbsf',f.size);await page.locator('#sbslimit').selectOption('1');await page.locator('#sbsgo').click();await expect(page.locator('#sbsdl')).toBeVisible({timeout:120000});const z=await dl(page,'#sbsdl','40-split.zip'),zip=await JSZip.loadAsync(await fs.readFile(z)),names=Object.keys(zip.files).filter(n=>n.endsWith('.pdf'));expect(names.length).toBeGreaterThan(1);let pages=0;for(const n of names){const bytes=await zip.file(n).async('uint8array');expect(bytes.length).toBeLessThanOrEqual(1048576);const d=await PDFDocument.load(bytes);pages+=d.getPageCount()}expect(pages).toBe(4)});
 test('41 PDF to long JPG outputs a real image',async({page})=>{await go(page,'longimage');await page.setInputFiles('#longf',f.base);await page.locator('#longscale').selectOption('0.9');await page.locator('#longgo').click();await expect(page.locator('#longdl')).toBeVisible({timeout:60000});const p=await dl(page,'#longdl','41-long.jpg');const b=await fs.readFile(p);expect([...b.slice(0,3)]).toEqual([255,216,255]);const meta=await sharp(b).metadata();expect(meta.height).toBeGreaterThan(meta.width*2)});
 test('42 Header Footer preserves pages and changes content',async({page})=>{await go(page,'headerfooter');await page.setInputFiles('#hff',f.base);await page.locator('#hfhead').fill('HỒ SƠ DHHD QA');await page.locator('#hffoot').fill('Trang {page}/{pages} - {date}');const p=await dl(page,'#hfgo','42-header-footer.pdf');await pdf(p,3);expect((await fs.stat(p)).size).toBeGreaterThan((await fs.stat(f.base)).size)});
 test('43 Annotation pointer draw exports valid changed PDF',async({page})=>{await go(page,'annotate');await page.setInputFiles('#annf',f.base);await expect(page.locator('#annlayer')).toBeVisible({timeout:30000});const box=await page.locator('#annlayer').boundingBox();await page.mouse.move(box.x+box.width*.2,box.y+box.height*.25);await page.mouse.down();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.4,{steps:15});await page.mouse.up();const p=await dl(page,'#anngo','43-annotated.pdf');await pdf(p,3);expect((await fs.stat(p)).size).toBeGreaterThan((await fs.stat(f.base)).size)});
 test('44 Deskew detects tilted scan, requires review, exports PDF',async({page})=>{await go(page,'deskew');await page.setInputFiles('#deskf',f.skew);await page.locator('#deskscan').click();await expect(page.locator('#deskapply')).toBeVisible({timeout:60000});await expect(page.locator('#deskresult')).toContainText('Lệch khoảng');const p=await dl(page,'#deskapply','44-deskew.pdf');await pdf(p,1)});
 test('45 PDF to Markdown detects heading and downloads MD',async({page})=>{await go(page,'markdown');await page.setInputFiles('#mdf',f.text);await page.locator('#mdgo').click();await expect(page.locator('#mdpreview')).toBeVisible({timeout:30000});const val=await page.locator('#mdpreview').inputValue();expect(val).toContain('DHHD MARKDOWN QA');expect(val).toContain('12345');expect(val).toMatch(/#\s+DHHD MARKDOWN QA/);const p=await dl(page,'#mddl','45-output.md');expect(await fs.readFile(p,'utf8')).toContain('<!-- Trang 1 -->')});
 test('46 public home exposes all six v0.7 tools and 41 total',async({page})=>{await page.goto(`${BASE}/#home`);await page.waitForFunction(()=>document.querySelectorAll('[data-tool-card]').length===41);await expect(page.locator('.hero .eyebrow')).toHaveText('DHHD TOOLS v0.7.0');await expect(page.getByText('41 công cụ hoạt động')).toBeVisible();for(const key of Object.keys(fn))await expect(page.locator(`[href="#${key}"]`)).toHaveCount(1)});
 test('47 mobile WebKit opens annotation and renders canvas',async()=>{const browser=await webkit.launch(),ctx=await browser.newContext({...devices['iPhone 13']}),page=await ctx.newPage();await page.goto(`${BASE}/#annotate`,{waitUntil:'load'});await page.waitForFunction(()=>typeof window.annotationTool==='function',{timeout:30000});await page.setInputFiles('#annf',f.base);await expect(page.locator('#annlayer')).toBeVisible({timeout:30000});const box=await page.locator('#annlayer').boundingBox();expect(box.width).toBeGreaterThan(250);await ctx.close();await browser.close()});
});
