import { test, expect, webkit, devices } from '@playwright/test';
import { PDFDocument, StandardFonts } from 'pdf-lib';
import JSZip from 'jszip';
import sharp from 'sharp';
import fs from 'node:fs/promises';
import path from 'node:path';

const BASE='https://dhhd-tools-v022.vercel.app';
const root=process.cwd(),fx=path.join(root,'.fixtures-v11'),out=path.join(root,'test-results','v11-downloads');
const f={a:path.join(fx,'wide.pdf'),b:path.join(fx,'portrait.pdf'),ocr1:path.join(fx,'ocr1.png'),ocr2:path.join(fx,'ocr2.png'),split:path.join(fx,'split.pdf')};

async function makePdf(file,size,count,prefix){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.HelveticaBold);for(let i=1;i<=count;i++){const p=pdf.addPage(size);p.drawText(`${prefix} PAGE ${i}`,{x:40,y:size[1]-80,size:24,font})}await fs.writeFile(file,await pdf.save())}
async function fixtures(){await fs.mkdir(fx,{recursive:true});await fs.mkdir(out,{recursive:true});await makePdf(f.a,[900,500],2,'WIDE');await makePdf(f.b,[500,900],1,'PORTRAIT');await makePdf(f.split,[595.28,841.89],23,'SPLIT');for(const [file,text] of [[f.ocr1,'HELLO DHHD ONE'],[f.ocr2,'HELLO DHHD TWO']]){const svg=`<svg width="1200" height="400" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" fill="white"/><text x="60" y="230" font-size="92" font-family="Arial" fill="black">${text}</text></svg>`;await fs.writeFile(file,await sharp(Buffer.from(svg)).png().toBuffer())}}
async function go(page,key){await page.goto(`${BASE}/#${key}`,{waitUntil:'load'});await page.waitForFunction(()=>!!window.PDFLib&&!!window.JSZip,null,{timeout:30000});await expect(page.locator('.toolHero h1')).toBeVisible({timeout:30000})}
async function dl(page,sel,name,timeout=240000){const wait=page.waitForEvent('download',{timeout});await page.locator(sel).click();const d=await wait,p=path.join(out,name);await d.saveAs(p);expect((await fs.stat(p)).size).toBeGreaterThan(80);return p}

test.beforeAll(fixtures);
test.describe.serial('DHHD v0.11 hidden production real-file gate',()=>{
 test('70 batch normalize returns two valid A4 PDFs in ZIP',async({page})=>{await go(page,'batchnormalize');await page.setInputFiles('#bnf',[f.a,f.b]);await page.locator('#bngo').click();await expect(page.locator('#bndl')).toBeVisible({timeout:90000});const z=await JSZip.loadAsync(await fs.readFile(await dl(page,'#bndl','70-normalize.zip'))),names=Object.keys(z.files).filter(n=>n.endsWith('.pdf')).sort();expect(names).toHaveLength(2);for(const n of names){const pdf=await PDFDocument.load(await z.file(n).async('uint8array'));for(const p of pdf.getPages()){const {width,height}=p.getSize(),dims=[+width.toFixed(1),+height.toFixed(1)].sort((a,b)=>a-b);expect(dims[0]).toBeCloseTo(595.3,0);expect(dims[1]).toBeCloseTo(841.9,0)}}});
 test('71 batch OCR recognizes two real images and ZIPs TXT results',async({page})=>{await go(page,'batchocr');await page.setInputFiles('#bof',[f.ocr1,f.ocr2]);await page.locator('#bolang').selectOption('eng');await page.locator('#bogo').click();await expect(page.locator('#bodl')).toBeVisible({timeout:240000});const z=await JSZip.loadAsync(await fs.readFile(await dl(page,'#bodl','71-ocr.zip'))),names=Object.keys(z.files).filter(n=>n.endsWith('.txt')).sort();expect(names).toHaveLength(2);const texts=[];for(const n of names)texts.push((await z.file(n).async('string')).toUpperCase());expect(texts.join('\n')).toContain('DHHD');expect(texts.join('\n')).toContain('ONE');expect(texts.join('\n')).toContain('TWO')});
 test('72 split by pages creates 3 PDFs with 10,10,3 pages',async({page})=>{await go(page,'splitbypages');await page.setInputFiles('#sbpf',f.split);await page.locator('#sbpn').selectOption('10');await page.locator('#sbpgo').click();await expect(page.locator('#sbpdl')).toBeVisible({timeout:90000});const z=await JSZip.loadAsync(await fs.readFile(await dl(page,'#sbpdl','72-split.zip'))),names=Object.keys(z.files).filter(n=>n.endsWith('.pdf')).sort();expect(names).toHaveLength(3);const counts=[];for(const n of names)counts.push((await PDFDocument.load(await z.file(n).async('uint8array'))).getPageCount());expect(counts).toEqual([10,10,3])});
 test('73 v0.11 remains hidden from public 50-tool home',async({page})=>{await page.goto(`${BASE}/#home`,{waitUntil:'load'});await page.waitForFunction(()=>document.querySelectorAll('[data-tool-card]').length===50,null,{timeout:30000});await expect(page.locator('.hero .eyebrow')).toHaveText('DHHD TOOLS v0.10.0');for(const key of ['batchnormalize','batchocr','splitbypages'])await expect(page.locator(`[href="#${key}"]`)).toHaveCount(0)});
 test('74 mobile WebKit opens all hidden v0.11 routes',async()=>{const browser=await webkit.launch(),ctx=await browser.newContext({...devices['iPhone 13']}),page=await ctx.newPage();for(const key of ['batchnormalize','batchocr','splitbypages']){await page.goto(`${BASE}/#${key}`,{waitUntil:'load'});await expect(page.locator('.toolHero h1')).toBeVisible({timeout:30000})}await ctx.close();await browser.close()});
});
